# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/IWA.NET.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'

stages:
- stage: Fortify
  jobs:
  - job: FortifySAST
    steps:
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '11'
        jdkArchitectureOption: x64
        jdkSourceOption: PreInstalled

    - task: BatchScript@1
      inputs:
        filename: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat'
        modifyEnvironment: true
    - task: FortifyScanCentralSAST@7
      inputs:
        scanCentralCtrlUrl: 'https://scsastctrl.uat.fortifyhosted.net/scancentral-ctrl'
        scanCentralClientToken: '$(clientToken)'
        sscUrl: 'https://ssc.uat.fortifyhosted.net'
        sscCiToken: '$(ciToken)'
        uploadToSSC: true
        applicationIdentifierType: 'byId'
        applicationVersionId: '16822'
        buildTool: 'msbuild'
        buildFile: 'IWA.NET.sln'
        buildCommand: '/t:rebuild'


- stage: Debricked
  jobs:
  - job: Debricked
    displayName: Fortify SCA (Debricked)
    steps:
      - script: mvn dependency:tree -DoutputFile=.debricked-maven-dependencies.tgf -DoutputType=tgf
        displayName: 'mvn dependency:tree'
      - script: |
          env > env.list
          docker run -v $HOME:$HOME --env-file ./env.list --entrypoint "/azure-devops.sh" debricked/debricked-scan:latest
        displayName: 'Debricked scan'
        env:
          DEBRICKED_TOKEN: $(DEBRICKED_TOKEN)


- stage: SummaryAndSync
  jobs:
  - job: SummaryAndSync
    displayName: Scan Summay and Sync
    container:
      image: fortifydocker/fortify-ci-tools:latest
 
    steps:
      - script: |
          echo Setting connection with Fortify Platform
          fcli ssc session login --url $(SSC_URL) -u $(SSC_USER) -p $(SSC_PASSWORD)
 
          echo Summary of Fortify Scan
          fcli ssc appversion-vuln count --appversion=$SSC_APP_VERSION_ID
 
          echo Start Synchronisation of Debricked results into Fortify
          fcli ssc appversion-artifact import debricked --appversion=$(SSC_APP_NAME):$(SSC_APP_VERSION) --repository=janwienand0361/IWA --branch=main -t=$(DEBRICKED_TOKEN)
 
          echo Logout and cleanup
          fcli ssc session logout -u $(SSC_USER) -p $(SSC_PASSWORD)
        displayName: Scan Summay and Sync