# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/IWA.NET.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'

steps:
- task: JavaToolInstaller@0
  inputs:
    versionSpec: '11'
    jdkArchitectureOption: x64
    jdkSourceOption: PreInstalled
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/IWA.NET.sln'
    feedsToUse: 'select'
- task: MSBuild@1
- task: BatchScript@1
  inputs:
    filename: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat'
    modifyEnvironment: true
- task: FortifyScanCentralSAST@7
  inputs:
    scanCentralCtrlUrl: 'https://scsastctrl.uat.fortifyhosted.net/scancentral-ctrl'
    scanCentralClientToken: '$(clientToken)'
    sscUrl: 'https://ssc.uat.fortifyhosted.net'
    sscCiToken: '$(ciToken)'
    uploadToSSC: true
    applicationIdentifierType: 'byId'
    applicationVersionId: '16821'
    buildTool: 'msbuild'
    buildFile: 'IWA.NET.sln'
    buildCommand: '/t:rebuild'