# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/IWA.NET.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'

stages:
- stage: Fortify
  jobs:
  - job: FortifySAST
    steps:
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '11'
        jdkArchitectureOption: x64
        jdkSourceOption: PreInstalled

    - task: BatchScript@1
      inputs:
        filename: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat'
        modifyEnvironment: true
    - task: FortifyScanCentralSAST@7
      inputs:
        scanCentralCtrlUrl: 'https://scsastctrl.uat.fortifyhosted.net/scancentral-ctrl'
        scanCentralClientToken: '$(clientToken)'
        sscUrl: '$(sscUrl)'
        sscCiToken: '$(ciToken)'
        uploadToSSC: true
        applicationIdentifierType: 'byId'
        applicationVersionId: $(appId)
        buildTool: 'msbuild'
        buildFile: 'IWA.NET.sln'
        buildCommand: '/t:rebuild'


- stage: Debricked
  jobs:
  - job: Debricked
    displayName: Fortify SCA (Debricked)
    continueOnError: true
    steps:
      - powershell: 'Invoke-Webrequest "https://github.com/debricked/cli/releases/latest/download/cli_windows_x86_64.tar.gz" -outfile debricked.tar.gz'
      - task: ExtractFiles@1
        inputs:
         archiveFilePatterns: "**/debricked.tar.gz"
         destinationFolder: $(Agent.ToolsDirectory)
         cleanDestinationFolder: false
      - script: |
          $(Agent.ToolsDirectory)/debricked.exe resolve
          $(Agent.ToolsDirectory)/debricked.exe scan
        displayName: 'Debricked scan'
        env:
          DEBRICKED_TOKEN: $(debrickedToken)


- stage: SummaryAndSync
  jobs:
  - job: SummaryAndSync
    displayName: Scan Summay and Sync
 
    steps:
      - powershell: 'Invoke-Webrequest "https://github.com/fortify/fcli/releases/download/v2.4.0/fcli-windows.zip" -outfile fcli.zip'
      - task: ExtractFiles@1
        inputs:
         archiveFilePatterns: "**/fcli.zip"
         destinationFolder: $(Agent.ToolsDirectory)
         cleanDestinationFolder: false
      - script: |
          echo Setting connection with Fortify Platform
          $(Agent.ToolsDirectory)/fcli.exe ssc session login --url $(sscUrl) -u $(sscUser) -p $(sscPassword)
 
          echo Summary of Fortify Scan
          $(Agent.ToolsDirectory)/fcli.exe ssc issue count --appversion=$(appId)
 
          echo Start Synchronisation of Debricked results into Fortify
          $(Agent.ToolsDirectory)/fcli.exe ssc artifact import-debricked --appversion=$(appId) --repository=80953 --branch= -t=$(debrickedToken)
 
          echo Logout and cleanup
          $(Agent.ToolsDirectory)/fcli.exe ssc session logout -u $(sscUser) -p $(sscPassword)
        displayName: Scan Summay and Sync